# Generated by Django 2.2.2 on 2019-06-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_reteta'),
    ]

    operations = [
        migrations.AddField(
            model_name='reteta',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
